# Generated by Django 4.0.5 on 2022-06-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Pwd', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
            ],
            options={
                'db_table': 'ecommerce_newuser',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Title', models.TextField(max_length=100)),
                ('Product_Price', models.IntegerField(max_length=10)),
                ('Product_Image', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ecommerce_product',
            },
        ),
    ]
