# Generated by Django 4.0.4 on 2022-07-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveIntegerField()),
                ('green', models.PositiveIntegerField()),
                ('orange', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default=None, max_length=30)),
                ('model', models.CharField(default=None, max_length=30)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('orange', 'Orange')], max_length=15)),
                ('width', models.CharField(choices=[('skinny', 'Skinny'), ('slim', 'Slim'), ('regular', 'Regular'), ('wide', 'Wide')], max_length=15)),
                ('height', models.CharField(choices=[('Mens', (('xxs', 'UK 26; Europe 42; USA 26; International XXS'), ('xs', 'UK 28; Europe 44; USA 28; International XS'), ('s', 'UK 30; Europe 46; USA 30; International S'), ('m', 'UK 32; Europe 48; USA 32; International M'), ('l', 'UK 34; Europe 50; USA 34; International L'), ('xl', 'UK 36; Europe 52; USA 36; International XL'), ('xxl', 'UK 38; Europe 54; USA 38; International XXL'), ('xxxl', 'UK 40; Europe 56; USA 40; International XXL'))), ('Women', (('xxs', 'UK 24; Europe 40; USA 24; International XXS'), ('xs', 'UK 26; Europe 42; USA 26; International XS'), ('s', 'UK 38; Europe 44; USA 38; International S'), ('m', 'UK 30; Europe 46; USA 30; International M'), ('l', 'UK 32; Europe 48; USA 32; International L'), ('xl', 'UK 34; Europe 50; USA 34; International XL'), ('xxl', 'UK 36; Europe 52; USA 36; International XXL'), ('xxxl', 'UK 38; Europe 54; USA 38; International XXL'))), ('Child', (('1 - 12 months', '1 - 12 months'), ('1 - 2 years', '1 - 2 years'), ('2 - 3 years', '2 - 3 years'), ('3 - 4 years', '3 - 4 years'), ('4 - 5 years', '4 - 5 years'), ('5 - 6 years', '5 - 6 years'), ('6 - 7 years', '6 - 7 years'), ('7 - 8 years', '7 - 8 years'), ('8 - 9 years', '8 - 9 years'), ('9 - 10 years', '9 - 10 years'), ('10 - 11 years', '10 - 11 years'), ('11 - 12 years', '11 - 12 years'), ('12 - 13 years', '12 - 13 years'), ('13 - 14 years', '13 - 14 years'))), ('unknown', 'Unknown')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(default='Red', max_length=3)),
                ('blue', models.CharField(default='Blue', max_length=4)),
                ('green', models.CharField(default='Green', max_length=5)),
                ('black', models.CharField(default='Black', max_length=5)),
                ('orange', models.CharField(default='Orange', max_length=6)),
                ('yellow', models.CharField(default='Yellow', max_length=6)),
            ],
            options={
                'verbose_name': 'Colour',
                'verbose_name_plural': 'Colours',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xxs', models.PositiveIntegerField()),
                ('xs', models.PositiveIntegerField()),
                ('m', models.PositiveIntegerField()),
                ('l', models.PositiveIntegerField()),
                ('xl', models.PositiveIntegerField()),
                ('xxl', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default=None, max_length=30)),
                ('model', models.CharField(default=None, max_length=30)),
                ('size', models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=3)),
                ('NO_of_availabile_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.productsize')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.productcolour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.productsize'),
        ),
    ]
