# Generated by Django 4.0.5 on 2022-06-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
