# Generated by Django 4.0.5 on 2022-06-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_userlogin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': 'New user', 'verbose_name_plural': 'New users'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'verbose_name': 'New user', 'verbose_name_plural': 'New users'},
        ),
        migrations.RenameField(
            model_name='userlogin',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='userlogin',
            old_name='password',
            new_name='Password',
        ),
        migrations.AlterModelTable(
            name='userlogin',
            table='ecommerce_loged_in_users',
        ),
    ]
