# Generated by Django 4.0.5 on 2022-06-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_alter_newuser_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogin',
            options={'verbose_name': 'Loged in user', 'verbose_name_plural': 'Loged in useres'},
        ),
    ]
