# Generated by Django 4.0.5 on 2022-06-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_alter_userlogin_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='Pwd',
            new_name='Password',
        ),
    ]
