# Generated by Django 4.0.5 on 2022-06-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_rename_pwd_newuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Status_Choices',
            field=models.CharField(choices=[('on_count', 'On count'), ('off_count', 'Off count')], default='off_count', max_length=10),
        ),
    ]
