# Generated by Django 4.0.5 on 2022-06-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_product_status_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Status_Choices',
            new_name='Status',
        ),
        migrations.AddField(
            model_name='product',
            name='Slug',
            field=models.SlugField(default=models.TextField(max_length=100), max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Price',
            field=models.IntegerField(),
        ),
    ]
