# Generated by Django 4.0.5 on 2022-06-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Slug',
            field=models.SlugField(max_length=250),
        ),
    ]
