# Generated by Django 4.0.5 on 2022-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='Username',
        ),
        migrations.AddField(
            model_name='newuser',
            name='Password2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='Password',
            field=models.CharField(max_length=50),
        ),
    ]
