# Generated by Django 4.0.5 on 2022-06-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0013_profile_delete_userlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='Password2',
            new_name='password2',
        ),
    ]
