# Generated by Django 3.2.7 on 2022-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0014_rename_email_newuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Number', models.IntegerField()),
                ('Order_Product', models.CharField(max_length=100)),
                ('Order_Product_Price', models.IntegerField()),
                ('Order_Product_Value', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ecommerce_order',
            },
        ),
    ]
