# Generated by Django 3.2.7 on 2022-07-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0015_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Order_Product_Image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
