# Generated by Django 3.2.7 on 2022-07-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0016_cart_order_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Order',
        ),
    ]
