# Generated by Django 3.2.7 on 2022-07-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0019_all_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Number', models.IntegerField()),
                ('Price', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Card_Number', models.BigIntegerField()),
                ('Expiration_Date', models.IntegerField()),
                ('Security_Code', models.IntegerField()),
                ('Date', models.CharField(max_length=10)),
                ('Time', models.CharField(max_length=10)),
            ],
        ),
    ]
